DROP DATABASE bar_norte_sur;
CREATE DATABASE bar_norte_sur;

USE bar_norte_sur;

CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(50) NOT NULL,
    avatar VARCHAR(100),
    registrationCode VARCHAR(100),
    role ENUM("admin", "normal") DEFAULT "normal"
);

CREATE TABLE comida (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(5000) NOT NULL,
    userId INT UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE comida_images (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    image VARCHAR(100) NOT NULL,
    comidaId INT UNSIGNED NOT NULL,
    FOREIGN KEY (comidaId) REFERENCES comida (id) ON DELETE CASCADE
);

CREATE TABLE comida_comentarios (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    comentario TEXT,
    userId INT UNSIGNED NOT NULL,
    comidaId INT UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (comidaId) REFERENCES comida (id) ON DELETE CASCADE
);

CREATE TABLE likes (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    userId INT UNSIGNED NOT NULL,
    comidaId INT UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (comidaId) REFERENCES comida (id) ON DELETE CASCADE
);
